### ISSUE TITLE
API Error adding movies

### ISSUE THREAD

**Issue by tkreindler** [sirk123au/ArrTools#10]
I can't figure this one out for the life of me, my config is as follows:

[radarr]
api_key = e980************1d787e91
baseurl = http://192.168.***.3:7878
urlbase = 
rootfolderpath = /media/movies/
searchForMovie = True
qualityProfileId = 1
omdbapi_key =

**Comment by tkreindler** [comment]
I get this result when running radarr_add_moves

[INFO] Downloading Radarr Movie Data. :)
[INFO] Found 708 Movies in radarr_backup.csv. :)
[ERROR] Sorry. We couldn't find any movies matching Tokyo Story (2020)
[ERROR] Sorry. We couldn't find any movies matching This Is Garth Brooks (1992)
[ERROR] Sorry. We couldn't find any movies matching Two Days, One Night: On Location (2015)
[INFO] Added 0 of 708 Movies, 0 already exists. ;)

**Comment by tkreindler** [comment]
Figured it out! I have custom quality profiles and removed the defaults so none of the defaults work. I figured out what quality profile my existing movies were using by sending the following request in vscode's rest http extension.

GET http://192.168.86.3:7878/api/v3/movie
Authorization: e980*************d787e91

Then looked at what quality id my other movies had (7) and used that in the script.

**Comment by tkreindler** [comment]
Reopening this issue because the script should really output an error on a bad quality id, would probably save many people like me untold hours.

**Comment by sirk123au** [comment]
All fixed :)
