### ISSUE TITLE
Experience issues with radarr_add_from_list

### ISSUE THREAD

**Issue by boff999** [sirk123au/ArrTools#12]
Hi,

Ive been trying to get a list from a CSV to radarr working but fail at almost the first hurdle!

I've added `qualityProfileId = 1` to the config but when I try to run the script I get the following error, which found to be from the def match_profile_id(id): function.

`[ERROR] Could not find profile_id for instance profile ID "1"`

If I change to `qualityProfileId = Any` which has an ID of 1 it runs but only detects films already in radarr and does not add any, nor give any output, I suspect because it's not adding a valid qualityProfileId so fails?

`[INFO] Downloading Radarr Movie Data. :)
[INFO] Found 50 Movies in movies.csv. :)
[INFO] tt2120120         Pixels (2015) already Exists in Radarr.
[INFO] tt3659388         The Martian (2015) already Exists in Radarr.
[INFO] tt1355644         Passengers (2016) already Exists in Radarr.
[INFO] Added 0 of 50 Movies, 3 already exists. ;)
`

Any ideas where I'm going wrong please?

**Comment by sirk123au** [comment]
curl -X GET "https://127.0.0.1:7878/radarr/api/v3/qualityProfile?apikey=API_KEY" -H "accept: application/json"

Run this and it will get all the profile IDs. Make sure you replace API_KEY with your radarr api key. 

Config has to be like this no quotation 
`qualityProfileId = HD-720p`
 `qualityProfileId = 1`


fixed an issue try pulling again for changes
