### ISSUE TITLE
Profile ID not found

### ISSUE THREAD

**Issue by darksector26** [sirk123au/ArrTools#15]
Hi think i'm probably missing something obvious but can't seem to see the issue. If i set profile id to 4 (or any of the standard numbers) i get the below error. 

[INFO] Downloading Radarr Movie Data. :)
[INFO] Found 314 Movies in /Users/****/Desktop/plex/movieimport.csv. :)
[ERROR] Could not find profile_id for instance profile ID "4"

If i set it to HD-1080P it looks like its trying to work however doesn't add any movies...

[INFO] Found 314 Movies in /Users/***/Desktop/plex/movieimport.csv. :)
[ERROR] Sorry. We couldn't find any movies matching Aquaman (2018)
[ERROR] Sorry. We couldn't find any movies matching Crocodile Dundee (1986)
[ERROR] Sorry. We couldn't find any movies matching Four Weddings and a Funeral (1994)
[INFO] tt0107290	 Jurassic Park (1993) already Exists in Radarr.
[ERROR] Sorry. We couldn't find any movies matching Mamma Mia: Here We Go Again! (2018)
[INFO] Added 0 of 314 Movies, 1 already exists. ;)

I've done a couple of GET commands and confirmed that profileid should be 4 just a standard radarr setup

config.ini
[radarr]
api_key = 3*****************e
baseurl = http://10.*****1:7878
urlbase = 
rootfolderpath = /data/media/movies/
searchForMovie = True
qualityProfileId = 4
omdbapi_key = f5a1532d;

**Comment by sirk123au** [comment]
Do you have a sample of the CSV file so I can check it out

**Comment by darksector26** [comment]
Hi this is a copy of the top few rows, it was an export of plex metadata.
If needed i can upload the csv somewhere and send a link

title,year,imdbid
45 Years,2015,tt3544082
Aladdin,1992,tt0103639
The Amazing Spider-Man,2012,tt0948470
Ant-Man,2015,tt0478970
Ant-Man and the Wasp,2018,tt5095030
Aquaman,2018,N/A
Arthur Christmas,2011,tt1430607
Austin Powers: The Spy Who Shagged Me,1999,tt0145660
The Avengers,2012,tt0848228
Avengers: Age of Ultron,2015,tt2395427
Avengers: Infinity War,2018,tt4154756
The Babadook,2014,tt2321549
Back to the Future,1985,tt0088763
Back to the Future Part II,1989,tt0096874
Back to the Future Part III,1990,tt0099088
Batman Begins,2005,tt0372784
Bean,1997,tt0118689
The BFG,1989,tt0096866
The BFG,2016,tt3691740
The Big Short,2015,tt1596363

**Comment by sirk123au** [comment]
Worked fine for me my config is 

```
[radarr]
api_key = 
baseurl = http://localhost:7878
urlbase = /radarr
rootfolderpath = /data/media/Movies/
searchForMovie = True
qualityProfileId = HD-720p
omdbapi_key = 
```

Do you use a urlbase to access Radarr eg. http://127.0.0.1/radarr

**Comment by sirk123au** [comment]
Found outdated urls in the api pull the source again and it should be working now.
