### ISSUE TITLE
Lidarr import says all artists already exist, but they don't

### ISSUE THREAD

**Issue by casualpie** [sirk123au/ArrTools#16]
Running lidarr_add_from_list.py against a CSV of just artist names results in the following:

tor@tor:~/ArrTools$ python3 lidarr_add_from_list.py /STORAGE/Music/list.csv
[INFO] Downloading Lidarr Artist Data. :)
[INFO] Found 538 Artists in /STORAGE/Music/list.csv. :)
[INFO] 21 Savage already Exists in Lidarr.
<... insert 537 similar lines here ...>
[INFO] Added 0 of 538 Artists, 538 Already Exist

The artists don't show up in Lidarr, nor are they reflected when running backup_lidarr_2csv.py

Thoughts?

**Comment by sirk123au** [comment]
Can you show me your configuration.

**Comment by casualpie** [comment]
[radarr]
api_key =
baseurl =
urlbase = ; Include URL Base if you have it enabled
rootfolderpath =
searchForMovie =
qualityProfileId =
omdbapi_key = ; sign up here for api key http://www.omdbapi.com/apikey.aspx

[sonarr]
api_key =
baseurl =
urlbase = ; Include URL Base if you have it enabled
rootfolderpath =
searchForShow =
qualityProfileId =
omdbapi_key =
tvdb_api =  ; sign up here for a api key https://thetvdb.com/api-information
tvdb_userkey =
tvdb_username =

[lidarr]
api_key = redacted
baseurl = http://localhost:8686
rootfolderpath = /STORAGE/Music

; Standard Profile ID
; 1 Any
; 2 SD
; 3 HD-720p
; 4 HD-1080p
; 5 Ultra-HD
; 6 HD - 720p/1080p

**Comment by casualpie** [comment]
Ah, I fixed it. 

I don't know why it took so long for me to think of it. I guess opening it with excel added a comma to every artist, leaving a blank but not "blank" id field.

I removed the extra commas, and it's running now.
