### ISSUE TITLE
The API endpoint in backup_radarr_2csv.py is incorrect

### ISSUE THREAD

**Issue by rapidbnnuy** [sirk123au/ArrTools#18]
The line that forms the URL of the endpoint:
    url = "{}/api/movie".format(baseurl)

Should be:
    url = "{}/api/v3/movie".format(baseurl)

For the latest versions of Radarr. This currently results in the user getting a "failed to connect to Radarr" message, when all of the settings are actually correct in the config.ini file.

The team here needs to decide if this needs some type of variable for the version of Radarr the user is running, or just to assume the latest version and patch this in.

**Comment by sirk123au** [comment]
Mate there is no team its just me and this is just a hobby if you want to update the code that's fine but i don't not use this code anymore.
