### ISSUE TITLE
Lidarr Support?

### ISSUE THREAD

**Issue by Springs87** [sirk123au/ArrTools#3]
Hi,

I've been using this to backup both my sonarr and 2 radarr instances.

Will you by any chance be supporting Lidarr in the future?

Thanks

**Comment by sirk123au** [comment]
Sure I will have a look today

**Comment by sirk123au** [comment]
if you are still interested i have added support for lidarr for backing up and restoring.

**Comment by Springs87** [comment]
Thanks will take a look
