### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by PeeVv** [sirk123au/ArrTools#7]
Firstly: great tool! Used it to import some ~150 movies. Had some issues though:

1. Requirments contains the logging module which is already present in Python3, so it gives an error when installing.

2. Had some trouble with the config because the inline comments were read as part of the variable. Inline comments don't work with the default CommentParser settings, but can work with the inline_comment_prefixes option set to ';'.

3. In radarr_add_from_list.py, in the function add_movie (line 77), the headers are set after the first if-statement. When imdbid == None, the headers are not set and an error pops up. Setting the headers before the if-else fixes this.

4. Same as 3, but with ProfileId at line 73.

5. I started with rootfolderpath without the trailing slash, which doesn't give errors but makes it so that it seems like every movie already exists in Radarr. Maybe alter the documentation to state the trailing slash is needed.

**Comment by sirk123au** [comment]
Thanks for the input i am not a python programmer so i am still getting used to it. I have attempted to fix all the issues that you have suggested. Pull for the updated changes.
