### ISSUE TITLE
More verbose prompts needed for get_imdbid.py

### ISSUE THREAD

**Issue by kylemd** [sirk123au/ArrTools#8]
I was trying to get a list of IMDB IDs so I can use these to run radarr_add_from_list.py.

However running get_imdbid.py produced no output and no changes to the destination CSV file.

Testing the search string in the script manually does the following, so it's not that:

`https://omdbapi.com/?t=Antz&apikey=APIKEY`

`{"Title":"Antz","Year":"1998","Rated":"PG","Released":"02 Oct 1998","Runtime":"83 min","Genre":"Animation, Adventure, Comedy, Family","Director":"Eric Darnell, Tim Johnson","Writer":"Todd Alcott (screenplay), Chris Weitz (screenplay), Paul Weitz (screenplay)","Actors":"Woody Allen, Dan Aykroyd, Anne Bancroft, Jane Curtin","Plot":"A rather neurotic ant tries to break from his totalitarian society while trying to win the affection of the princess he loves.","Language":"English","Country":"USA","Awards":"Nominated for 1 BAFTA Film Award. Another 6 wins & 13 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMzMzMDdlMDktODg4OC00Y2E5LTk1ZjMtNzM2MzIxZGQ0ZGI3XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.5/10"},{"Source":"Rotten Tomatoes","Value":"92%"},{"Source":"Metacritic","Value":"72/100"}],"Metascore":"72","imdbRating":"6.5","imdbVotes":"145,976","imdbID":"tt0120587","Type":"movie","DVD":"N/A","BoxOffice":"$90,757,863","Production":"DreamWorks SKG, Pacific Data Images (PDI)","Website":"N/A","Response":"True"}`

The issues was my CSV file was Title,Year. If only the names are fed in, it works.
You may want to add a prompt when incorrect input is detected.

**Comment by sirk123au** [comment]
I have rewritten this to match the correct Movie. Pull to get changes.
